[workspace]
resolver = "2"
members = ["cargo-paradedb", "pg_search", "tests", "tokenizers"]

[profile.dev]
panic = "unwind"

[profile.release]
lto = "fat"
panic = "unwind"
opt-level = 3
codegen-units = 1

[profile.prof]
inherits = "release"
debug = true
lto = "thin"
codegen-units = 32
