[package]
name = "pg_search"
description = "Full text search for PostgreSQL using BM25"
version = "0.11.1"
edition = "2021"
license = "AGPL-3.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["pg16"]
pg13 = ["pgrx/pg13"]
pg14 = ["pgrx/pg14"]
pg15 = ["pgrx/pg15"]
pg16 = ["pgrx/pg16"]
pg17 = ["pgrx/pg17"]
pg_test = []
icu = ["tokenizers/icu"]

[dependencies]
anyhow = { version = "1.0.87", features = ["backtrace"] }
chrono = "0.4.38"
crossbeam = "0.8.4"
derive_more = "0.99.18"
fs2 = "0.4.3"
humansize = "2.1.3"
json5 = "0.4.1"
libc = "0.2.158"
memoffset = "0.9.1"
once_cell = "1.19.0"
os_info = { version = "3", default-features = false }
parking_lot = "0.12.3"
tokenizers = { path = "../tokenizers" }
pgrx = "0.12.6"
reqwest = { version = "0.11.27", features = ["blocking"] }
rustc-hash = "1.1.0"
serde = "1.0.210"
serde_json = "1.0.128"
tantivy = { git = "https://github.com/paradedb/tantivy.git", package = "tantivy", rev = "e4e9eb5" }
tantivy-common = { git = "https://github.com/paradedb/tantivy.git", rev = "e4e9eb5" }
thiserror = "1.0.63"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
walkdir = "2.5.0"
ordered-float = "4.2.2"
uuid = "1.10.0"
url = "2.5.2"
strum = { version = "0.26.3" }

[dev-dependencies]
fixture = "0.3.1"
rstest = "0.23.0"
tempfile = "3.13.0"


[package.metadata.cargo-machete]
ignored = ["indexmap", "libc", "tantivy-common"]

[[bin]]
name = "pgrx_embed_pg_search"
path = "./src/bin/pgrx_embed.rs"
