# workflows/benchmark-pg_search.yml
#
# Benchmark pg_search
# Benchmark pg_search performance on a nightly basis. This workflow can also be triggered
# manually to benchmark other systems on one-off basis, to compare against pg_search.

name: Benchmark pg_search

on:
  schedule:
    - cron: "1 0 * * 1,2,3,4,5" # Run once per day on weekdays (days of the week 1-5) at 00:01 UTC
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - dev
      - main
    paths:
      - ".github/workflows/benchmark-pg_search.yml"
      - "cargo-paradedb/**"
      - "docker/Dockerfile"
      - "pg_search/**"
      - "!pg_search/README.md"
      - "tokenizers/Cargo.toml"
  push:
    branches:
      - dev # Also run on dev to fill the GitHub Actions Rust cache in a way that pull requests can see it
    paths:
      - "**/*.rs"
      - "**/*.toml"
  workflow_dispatch:

concurrency:
  group: benchmark-pg_search-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  benchmark-pg_search:
    name: Benchmark pg_search
    runs-on: ubicloud-standard-8
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        pg_version: [17]

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install & Configure Supported PostgreSQL Version
        run: |
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          sudo apt-get update && sudo apt-get install -y postgresql-${{ matrix.pg_version }} postgresql-server-dev-${{ matrix.pg_version }}
          sudo chown -R $(whoami) /usr/share/postgresql/${{ matrix.pg_version }}/ /usr/lib/postgresql/${{ matrix.pg_version }}/ /var/lib/postgresql/${{ matrix.pg_version }}/
          echo "/usr/lib/postgresql/${{ matrix.pg_version }}/bin" >> $GITHUB_PATH

      - name: Extract pgrx Version
        id: pgrx
        working-directory: pg_search/
        run: echo version=$(cargo tree --depth 1 -i pgrx -p pg_search | head -n 1 | cut -f2 -dv) >> $GITHUB_OUTPUT

      - name: Install Rust Cache
        uses: ubicloud/rust-cache@v2
        with:
          prefix-key: "v1-rust"
          key: ${{ matrix.pg_version }}-${{ steps.pgrx.outputs.version }}
          cache-targets: true
          cache-all-crates: true

      - name: Install pgrx & pg_search
        working-directory: pg_search/
        run: |
          cargo install -j $(nproc) --locked cargo-pgrx --version ${{ steps.pgrx.outputs.version }} --debug
          cargo pgrx init --pg${{ matrix.pg_version }}=/usr/lib/postgresql/${{ matrix.pg_version }}/bin/pg_config
          cargo pgrx install --pg-config="/usr/lib/postgresql/${{ matrix.pg_version }}/bin/pg_config" --release

      - name: Add pg_search to shared_preload_libraries
        working-directory: /home/runner/.pgrx/data-${{ matrix.pg_version }}/
        run: sed -i "s/^#shared_preload_libraries = .*/shared_preload_libraries = 'pg_search'/" postgresql.conf

      - name: Install the ParadeDB Benchmarking Tool
        working-directory: cargo-paradedb/
        run: cargo run install

      - name: Start Postgres
        working-directory: pg_search/
        run: cargo pgrx start pg${{ matrix.pg_version }}

      - name: Generate Benchmark Data
        working-directory: pg_search/
        run: cargo paradedb bench eslogs generate --events 5000000 --url postgresql://localhost:288${{ matrix.pg_version }}/postgres

      - name: Index Benchmark Data
        working-directory: pg_search/
        run: cargo paradedb bench eslogs build-search-index --url postgresql://localhost:288${{ matrix.pg_version }}/postgres

      - name: Run Search Benchmark
        working-directory: pg_search/
        run: cargo paradedb bench eslogs query-search-index --url postgresql://localhost:288${{ matrix.pg_version }}/postgres

      # On `dev` and `main`, we store the benchmark results as artifact to serve as a comparison point for PRs
      - name: Store Benchmark Results (dev or main, push only)
        if: (github.ref == 'refs/heads/dev' && github.event_name == 'push') || (github.ref == 'refs/heads/main' && github.event_name == 'push')
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-pg_search-criterion-${{ github.ref_name }}
          path: target/criterion/

      - name: Download Benchmark Baseline (PRs only)
        if: github.event_name == 'pull_request'
        id: download_baseline
        env:
          GH_TOKEN: ${{ github.token }} # Required by `gh`
        continue-on-error: true # TODO: Remove this once we have a baseline to compare against in `main`
        run: |
          # We retrieve the latest successful benchmark run ID on `dev` or `main` that is a push event, since we only store artifacts on push,
          # to know which GitHub Artifact to download
          LATEST_RUN_ID=$(gh api \
            repos/paradedb/paradedb/actions/workflows/benchmark-pg_search.yml/runs \
            --jq '.workflow_runs[] | select(.head_branch == "${{ github.ref_name }}" and .conclusion == "success" and .event == "push") | .id' \
            | head -n 1)
          echo "Latest \`dev\` benchmark-pg_search run ID: $LATEST_RUN_ID"

          # This automatically unzips the downloaded artifact, which extracts the output.json file
          gh run download $LATEST_RUN_ID \
            --repo paradedb/paradedb \
            --name benchmark-pg_search-criterion-${{ github.ref_name }} \
            --dir ./previous/
          ls -l ./previous/

      - name: Compare Benchmark Results (PRs only)
        if: steps.download_baseline.outcome == 'success' && github.event_name == 'pull_request'
        id: compare_benchmarks
        continue-on-error: true # This is necessary as critcmp will error if there are no changes
        run: |
          cargo install -j $(nproc) --locked critcmp --debug
          result=$(critcmp ./previous/ target/criterion/)
          echo "Generating GitHub comment message"
          {
            echo 'DIFF<<EOF'
            echo 'Performance comparison (latest commit) with `dev`:'
            echo
            echo "$result"
            echo
            echo 'EOF'
          } >> "$GITHUB_ENV"

      - name: Attach Performance Comparison to PR (PRs only)
        if: steps.compare_benchmarks.outcome == 'success' && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const comments = await github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const botComment = comments.data.find(comment => comment.user.type === 'Bot' && comment.body.includes('Performance comparison (latest commit) with `dev`:'));

            if (botComment) {
              // Update the existing comment
              await github.rest.issues.updateComment({
                comment_id: botComment.id,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: process.env.DIFF
              });
            } else {
              // Create a new comment if none exists
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: process.env.DIFF
              });
            }

      - name: Notify Slack on Failure
        if: failure() && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main')
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Benchmark pg_search Workflow failed in `paradedb/paradedb` -- investigate immediately!"}' ${{ secrets.SLACK_WEBHOOK_URL }}
